### ISSUE TITLE
[1.12.2] SweepAttackParticle: java.lang.RuntimeException: Unable to find core.particles.ParticleParam (ParticleParam)

### ISSUE THREAD

**Issue by TUBEOF** [YourGameSpace/AntiCooldown#34]
`[10:48:47 ERROR]: [AntiCooldown] Unhandled exception occured in onPacketSending(PacketEvent) for AntiCooldown
java.lang.RuntimeException: Unable to find core.particles.ParticleParam (ParticleParam)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2159) ~[?:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getParticleParam(MinecraftReflection.java:2246) ~[?:?]
        at com.comphenix.protocol.events.AbstractStructure.getNewParticles(AbstractStructure.java:735) ~[?:?]
        at com.yourgamespace.anticooldown.listener.SweepAttack$PacketHandler$1.onPacketSending(SweepAttack.java:69) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1470) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.WorldServer.sendParticles(WorldServer.java:1454) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.WorldServer.sendParticles(WorldServer.java:1440) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:189) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:803) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:743) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[10:48:47 ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutWorldParticles@1533c1e[
    a=BLOCK_DUST
    b=16.504358
    c=79.0
    d=11.053609
    e=0.0
    f=0.0
    g=0.0
    h=0.15
    i=40
    j=false
    k={112}
  ]`

**Comment by ThoD4v** [comment]
This issue was fixed in https://github.com/YourGameSpace/AntiCooldown/commit/e665f9306d7e93e5a0e796168b47f76fe59b337e

**Comment by TUBEOF** [comment]
Merge into stable pending
Already fixed in this dev-build: https://hub.yourgamespace.com/jenkins/job/AntiCooldown-Dev/172/artifact/target/AntiCooldown-SNAPSHOT-172.jar
