### ISSUE TITLE
Update for 1.19.3 required

### ISSUE THREAD

**Issue by Outfluencer** [YourGameSpace/AntiCooldown#51]
[00:04:05 ERROR]: [AntiCooldown] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for AntiCooldown
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:218) ~[ProtocolLib.jar:?]
        at com.yourgamespace.anticooldown.listener.CombatSounds$PacketHandler$1.onPacketSending(CombatSounds.java:32) ~[AntiCooldown.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2161) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2147) ~[?:?]
        at net.minecraft.server.players.PlayerList.broadcast(PlayerList.java:1245) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.level.ServerLevel.playSeededSound(ServerLevel.java:1617) ~[?:?]
        at net.minecraft.world.level.Level.playSeededSound(Level.java:826) ~[?:?]
        at net.minecraft.world.level.Level.playSound(Level.java:832) ~[?:?]
        at net.minecraft.world.entity.Entity.playSound(Entity.java:1592) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.world.entity.Mob.playAmbientSound(Mob.java:322) ~[?:?]
        at net.minecraft.world.entity.Mob.baseTick(Mob.java:333) ~[?:?]
        at net.minecraft.world.entity.Entity.tick(Entity.java:777) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2968) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:402) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:292) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1213) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:918) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:733) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:713) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-319]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-319]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Outfluencer** [comment]
looks like protocol changes in 1.19.3
